# application.yml
server:
  port: 8802

spring:
  application:
    name: SERVER-SERVICE
  profiles:
    # 环境标识
    active: DEV

  config:
    import:
      - optional:nacos:COMMON-SERVICE-${spring.profiles.active}.yaml?group=COMMON_GROUP

  cloud:
    nacos:
      discovery:
        server-addr: 124.223.100.39:8848
        username: "nacos"
        password: "hH1234568."
      config:
        server-addr: 124.223.100.39:8848
        group: COMMON_GROUP
        file-extension: yaml
        refresh-enabled: true
        namespace: ""
        username: "nacos"
        password: "hH1234568."
